services:
  db:
    container_name: notes-db
    profiles:
     - https
     - http
    image: postgres:17
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-service:
    container_name: notes-email-service
    profiles:
     - https
     - http
    build:
      context: .
      dockerfile: email-service/Dockerfile
      target: final
    expose:
      - 8001
    volumes:
      - ./email-service/config.yaml:/app/config.yaml:ro
    restart: unless-stopped

  server1:
    container_name: notes-server-1
    profiles:
     - https
     - http
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server2:
    container_name: notes-server-2
    profiles:
     - https
     - http
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server3:
    container_name: notes-server-3
    profiles:
     - https
     - http
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  custom-balancer-http:
    container_name: notes-custom-balancer-http
    profiles:
     - http
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
      - 5000:5000
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/config.yaml:/app/config.yaml:ro
    depends_on:
      - server1
      - server2
      - server3
    restart: unless-stopped

  custom-balancer-https:
    container_name: notes-custom-balancer-https
    profiles:
     - https
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
      - 5000:5000
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/config.yaml:/app/config.yaml:ro
      - ./certs/servercert.pem:/app/certs/servercert.pem:ro
      - ./certs/serverkey.pem:/app/certs/serverkey.pem:ro
    depends_on:
      - server1
      - server2
      - server3
    restart: unless-stopped

volumes:
  db-data: {}
  target: {}
  cargo-cache: {}
