services:
  # Nginx load balancer
  nginx:
    container_name: notes-nginx
    image: nginx:alpine
    ports:
      - 4000:80
    volumes:
      - ./notes-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    profiles:
      - release-nginx
    restart: unless-stopped

  # Custom Rust load balancer
  custom-balancer:
    container_name: notes-custom-balancer
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
    environment:
      - RUST_LOG=debug
    volumes:
      - ./load-balancer/config.yaml:/app/config.yaml:ro
    depends_on:
      - server1
      - server2
      - server3
    profiles:
      - release-custom-balancer
    restart: unless-stopped

  # Server instance 1
  server1:
    container_name: notes-server-1
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-nginx
      - release-custom-balancer
      - release-multi-tier
    restart: unless-stopped

  # Server instance 2
  server2:
    container_name: notes-server-2
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-nginx
      - release-custom-balancer
      - release-multi-tier
    restart: unless-stopped

  # Server instance 3
  server3:
    container_name: notes-server-3
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-nginx
      - release-custom-balancer
      - release-multi-tier
    restart: unless-stopped

  # Server instance 4
  server4:
    container_name: notes-server-4
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-multi-tier
    restart: unless-stopped

  # Server instance 5
  server5:
    container_name: notes-server-5
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-multi-tier
    restart: unless-stopped

  # Server instance 6
  server6:
    container_name: notes-server-6
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release-multi-tier
    restart: unless-stopped

  # Secondary load balancer 1 (handles server1, server2, server3)
  secondary-lb-1:
    container_name: notes-secondary-lb-1
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    expose:
      - "8080"
    # environment:
      # - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.secondary.1.yaml:/app/config.yaml:ro
    depends_on:
      - server1
      - server2
      - server3
    profiles:
      - release-multi-tier
    restart: unless-stopped

  # Secondary load balancer 2 (handles server4, server5, server6)
  secondary-lb-2:
    container_name: notes-secondary-lb-2
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    expose:
      - "8080"
    # environment:
      # - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.secondary.2.yaml:/app/config.yaml:ro
    depends_on:
      - server4
      - server5
      - server6
    profiles:
      - release-multi-tier
    restart: unless-stopped

  # Primary load balancer (handles secondary-lb-1 and secondary-lb-2)
  primary-lb:
    container_name: notes-primary-lb
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
    # environment:
      # - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.primary.yaml:/app/config.yaml:ro
    depends_on:
      - secondary-lb-1
      - secondary-lb-2
    profiles:
      - release-multi-tier
    restart: unless-stopped

  server-dev:
    container_name: notes-server-dev
    build:
      context: .
      dockerfile: notes-server/Dockerfile.dev
    ports:
      - 4000:8000
      - 5000:50051
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    volumes:
      - ./grpc-client:/app/grpc-client:ro
      - ./notes-server:/app/notes-server:ro
      - ./proto:/app/proto:ro
      - ./target:/app/target
      - ./Cargo.lock:/app/Cargo.lock:ro
      - ./Cargo.toml:/app/Cargo.toml:ro
      - cargo-cache:/usr/local/cargo/registry
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - debug
  db:
    container_name: notes-db
    image: postgres:17
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - debug
      - release-nginx
      - release-custom-balancer
      - release-multi-tier
volumes:
  db-data: {}
  target:
  cargo-cache: {}

