services:
  db:
    container_name: notes-db
    profiles:
     - http
     - https
    image: postgres:17
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-service:
    container_name: notes-email-service
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: email-service/Dockerfile
      target: final
    expose:
      - 8001
    volumes:
      - ./email-service/config.yaml:/app/config.yaml:ro
    restart: unless-stopped

  server1:
    container_name: notes-server-1
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server2:
    container_name: notes-server-2
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server3:
    container_name: notes-server-3
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server4:
    container_name: notes-server-4
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server5:
    container_name: notes-server-5
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server6:
    container_name: notes-server-6
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  # Secondary load balancers
  secondary-lb-1:
    container_name: notes-secondary-lb-1
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    expose:
      - "8080"
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.secondary.1.yaml:/app/config.yaml:ro
    depends_on:
      - server1
      - server2
      - server3
    restart: unless-stopped

  secondary-lb-2:
    container_name: notes-secondary-lb-2
    profiles:
     - http
     - https
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    expose:
      - "8080"
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.secondary.2.yaml:/app/config.yaml:ro
    depends_on:
      - server4
      - server5
      - server6
    restart: unless-stopped

  # Primary load balancer (https)
  primary-lb-http:
    container_name: notes-primary-lb-http
    profiles:
     - http
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
      - 5000:5000
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.primary.yaml:/app/config.yaml:ro
    depends_on:
      - secondary-lb-1
      - secondary-lb-2
    restart: unless-stopped

  # Primary load balancer (https)
  primary-lb-https:
    container_name: notes-primary-lb-https
    profiles:
     - https
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
      target: final
    ports:
      - 4000:8080
      - 5000:5000
    # environment:
    #   - RUST_LOG=debug
    volumes:
      - ./load-balancer/configs/config.primary.yaml:/app/config.yaml:ro
      - ./notes-server/certs/servercert.pem:/app/certs/servercert.pem:ro
      - ./notes-server/certs/serverkey.pem:/app/certs/serverkey.pem:ro
    depends_on:
      - secondary-lb-1
      - secondary-lb-2
    restart: unless-stopped

volumes:
  db-data: {}
  target: {}
  cargo-cache: {}
