services:
  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    profiles:
      - release
    restart: unless-stopped

  # Server instance 1
  server1:
    build:
      context: .
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release
    restart: unless-stopped

  # Server instance 2
  server2:
    build:
      context: .
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release
    restart: unless-stopped

  # Server instance 3
  server3:
    build:
      context: .
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - release
    restart: unless-stopped

  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:8000
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
    volumes:
      - ./src:/app/src:ro
      - ./Cargo.toml:/app/Cargo.toml:ro
      - ./Cargo.lock:/app/Cargo.lock:ro
      - target:/app/target
      - cargo-cache:/usr/local/cargo/registry
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - debug
  db:
    image: postgres:17
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - debug
      - release
volumes:
  db-data: {}
  target:
  cargo-cache: