services:
  db:
    container_name: notes-db
    image: postgres:17
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-service:
    container_name: notes-email-service
    build:
      context: .
      dockerfile: email-service/Dockerfile
      target: final
    expose:
      - 8001
    volumes:
      - ./email-service/config.yaml:/app/config.yaml:ro
    restart: unless-stopped

  server1:
    container_name: notes-server-1
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server2:
    container_name: notes-server-2
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  server3:
    container_name: notes-server-3
    build:
      context: .
      dockerfile: notes-server/Dockerfile
      target: final
    environment:
      - PG_DSN=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=debug
      - EMAIL_SERVICE_URL=http://email-service:8001
    depends_on:
      db:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  nginx:
    container_name: notes-nginx
    image: nginx:alpine
    ports:
      - 4000:80 # HTTP
      - 4443:443 # HTTPS
      - 5000:5000 # gRPC HTTPS
    volumes:
      - ./notes-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/servercert.pem:/etc/ssl/certs/notes.pem:ro
      - ./certs/serverkey.pem:/etc/ssl/private/notes.pem:ro
    depends_on:
      - server1
      - server2
      - server3
    restart: unless-stopped

volumes:
  db-data: {}
  target: {}
  cargo-cache: {}
