instances:
  - base_url: "http://secondary-lb-1"
    rest_port: 8080
    grpc_port: 5000
  - base_url: "http://secondary-lb-2"
    rest_port: 8080
    grpc_port: 5000
rest_port: 8080
grpc_port: 5000
strategy: "round_robin"
health_check_interval: "2s"
health_check_time_limit: "10s"
connection_timeout: "2s"
max_retries: 3
