urls:
  - "http://server4:8000"
  - "http://server5:8000"
  - "http://server6:8000"
port: 8080
strategy: "round_robin"
health_check_interval: "2s"
health_check_time_limit: "10s"
connection_timeout: "2s"
